import { ApplicationConfig, provideBrowserGlobalErrorListeners, isDevMode } from '@angular/core';
import { provideRouter } from '@angular/router';
import { routes } from './app.routes';
import { provideServiceWorker } from '@angular/service-worker';
import { provideTablerIcons } from '@tabler/icons-angular';
import {
  IconHome,
  IconToolsKitchen2,
  IconBook2,
  IconWalk,
  IconAlarm,
  IconActivityHeartbeat,
  IconLeaf,
  IconEgg,
  IconMeat,
  IconFish,
  IconCheese,
  IconBowlFilled,
  IconSoupFilled,
  IconBowl,
  IconBread,
  IconSeedling,
  IconWheat,
  IconAvocado,
  IconSphere,
  IconCoffee,
  IconMug,
  IconDroplet,
  IconGlass,
  IconGlassFull,
  IconBan,
  IconStepInto,
  IconPlus,
  IconMinus,
  IconCheck,
  IconX,
  IconAlertTriangle,
  IconChevronRight,
  IconClock,
  IconBell,
  IconDeviceFloppy,
  IconVolume,
  IconVolumeOff,
  IconTrash,
  IconCalendarEvent,
  IconHeartbeat,
  IconMoon,
  IconTarget,
  IconBulb,
  IconStethoscope,
  IconSearch,
  IconCarrot,
  IconPepper,
  IconMushroom,
  IconApple,
  IconLemon,
  IconGrape,
} from '@tabler/icons-angular';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes),
    provideServiceWorker('ngsw-worker.js', {
      enabled: !isDevMode(),
      registrationStrategy: 'registerWhenStable:30000',
    }),
    provideTablerIcons({
      IconHome,
      IconToolsKitchen2,
      IconBook2,
      IconWalk,
      IconAlarm,
      IconActivityHeartbeat,
      IconLeaf,
      IconEgg,
      IconMeat,
      IconFish,
      IconCheese,
      IconBowlFilled,
      IconSoupFilled,
      IconBowl,
      IconBread,
      IconSeedling,
      IconWheat,
      IconAvocado,
      IconSphere,
      IconCoffee,
      IconMug,
      IconDroplet,
      IconGlass,
      IconGlassFull,
      IconBan,
      IconStepInto,
      IconPlus,
      IconMinus,
      IconCheck,
      IconX,
      IconAlertTriangle,
      IconChevronRight,
      IconClock,
      IconBell,
      IconDeviceFloppy,
      IconVolume,
      IconVolumeOff,
      IconTrash,
      IconCalendarEvent,
      IconHeartbeat,
      IconMoon,
      IconTarget,
      IconBulb,
      IconStethoscope,
      IconSearch,
      IconCarrot,
      IconPepper,
      IconMushroom,
      IconApple,
      IconLemon,
      IconGrape,
    }),
  ],
};