import type { Alimento } from '../modelo/modelo';

export const alimentos: Alimento[] = [
  // ── Verduras: libres ─────────────────────────────────────────────
  {
    id: 'nopales',
    nombre: 'Nopales',
    categoria: 'verdura',
    carbs: 0,
    porcion: '1 taza',
    explicacion: 'Ayudan a bajar el azucar despues de comer.',
    icono: 'icon-leaf',
    semaforo: 'verde',
    consultaUsda: 'nopales cooked',
  },
  {
    id: 'calabacitas',
    nombre: 'Calabacitas',
    categoria: 'verdura',
    carbs: 0,
    porcion: '1 taza',
    explicacion: 'Ligera, llena y con fibra.',
    icono: 'icon-leaf',
    semaforo: 'verde',
    consultaUsda: 'summer squash zucchini cooked',
  },
  {
    id: 'chayotes',
    nombre: 'Chayotes',
    categoria: 'verdura',
    carbs: 0,
    porcion: '1 taza',
    explicacion: 'Verdura suave y digestiva.',
    icono: 'icon-leaf',
    semaforo: 'verde',
    consultaUsda: 'chayote cooked boiled',
  },
  {
    id: 'espinacas',
    nombre: 'Espinacas',
    categoria: 'verdura',
    carbs: 0,
    porcion: '1 taza',
    explicacion: 'Ricas en vitaminas, casi sin azucar.',
    icono: 'icon-leaf',
    semaforo: 'verde',
    consultaUsda: 'spinach cooked boiled',
  },
  {
    id: 'ejotes',
    nombre: 'Ejotes',
    categoria: 'verdura',
    carbs: 0,
    porcion: '1 taza',
    explicacion: 'Fibra que ayuda a sentirte satisfecha.',
    icono: 'icon-leaf',
    semaforo: 'verde',
    consultaUsda: 'green snap beans cooked',
  },
  {
    id: 'brocoli',
    nombre: 'Brocoli',
    categoria: 'verdura',
    carbs: 0,
    porcion: '1 taza',
    explicacion: 'Llenador y muy nutritivo.',
    icono: 'icon-leaf',
    semaforo: 'verde',
    consultaUsda: 'broccoli cooked boiled',
  },
  {
    id: 'lechuga',
    nombre: 'Lechuga',
    categoria: 'verdura',
    carbs: 0,
    porcion: '2 tazas',
    explicacion: 'Es la base de una ensalada fresca.',
    icono: 'icon-leaf',
    semaforo: 'verde',
    consultaUsda: 'lettuce green leaf raw',
  },
  {
    id: 'pepino',
    nombre: 'Pepino',
    categoria: 'verdura',
    carbs: 0,
    porcion: '1 taza',
    explicacion: 'Refrescante y con mucha agua.',
    icono: 'icon-leaf',
    semaforo: 'verde',
    consultaUsda: 'cucumber with peel raw',
  },

  // ── Proteinas ────────────────────────────────────────────────────
  {
    id: 'huevo',
    nombre: 'Huevo',
    categoria: 'proteina',
    carbs: 0,
    porcion: '2 piezas',
    explicacion: 'Proteina completa que no sube el azucar.',
    icono: 'icon-egg',
    semaforo: 'verde',
    consultaUsda: 'egg whole hard-boiled',
  },
  {
    id: 'pechuga-pollo',
    nombre: 'Pechuga de pollo',
    categoria: 'proteina',
    carbs: 0,
    porcion: '1/2 pieza',
    explicacion: 'Carne magra ideal todos los dias.',
    icono: 'icon-meat',
    semaforo: 'verde',
    consultaUsda: 'chicken breast grilled broiled',
  },
  {
    id: 'pescado',
    nombre: 'Pescado',
    categoria: 'proteina',
    carbs: 0,
    porcion: '1 filete',
    explicacion: 'Corazon sano y proteinas de calidad.',
    icono: 'icon-fish',
    semaforo: 'verde',
    consultaUsda: 'tilapia cooked',
  },
  {
    id: 'bistec-res',
    nombre: 'Bistec de res',
    categoria: 'proteina',
    carbs: 0,
    porcion: '1 pieza',
    explicacion: 'Elige cortes sin grasa visible.',
    icono: 'icon-meat',
    semaforo: 'verde',
    consultaUsda: 'beef sirloin steak grilled',
  },
  {
    id: 'panela',
    nombre: 'Queso panela',
    categoria: 'proteina',
    carbs: 0,
    porcion: '1 rebanada',
    explicacion: 'Queso suave y bajo en grasa.',
    icono: 'icon-cheese',
    semaforo: 'verde',
    consultaUsda: 'cheese panela',
  },
  {
    id: 'oaxaca',
    nombre: 'Queso oaxaca',
    categoria: 'proteina',
    carbs: 0,
    porcion: '3 hebras',
    explicacion: 'Delicioso con moderacion.',
    icono: 'icon-cheese',
    semaforo: 'verde',
    consultaUsda: 'cheese oaxaca',
  },

  // ── Carbohidratos fuertes: 1 punto, se excluyen entre si ─────────
  {
    id: 'arroz',
    nombre: 'Arroz',
    categoria: 'carbohidrato-fuerte',
    carbs: 1,
    porcion: '1/2 taza',
    explicacion: 'Sube el azucar rapido, porcion muy pequeña.',
    icono: 'icon-bowl-filled',
    semaforo: 'amarillo',
    consultaUsda: 'rice white cooked',
  },
  {
    id: 'sopa-pasta',
    nombre: 'Sopa de pasta',
    categoria: 'carbohidrato-fuerte',
    carbs: 1,
    porcion: '1/2 taza',
    explicacion: 'Un solo platillo de carbohidrato por comida.',
    icono: 'icon-soup-filled',
    semaforo: 'amarillo',
    consultaUsda: 'pasta cooked enriched',
  },
  {
    id: 'papa',
    nombre: 'Papa hervida',
    categoria: 'carbohidrato-fuerte',
    carbs: 1,
    porcion: '1/2 taza',
    explicacion: 'Cuidado: sube el azucar pronto.',
    icono: 'icon-bowl',
    semaforo: 'amarillo',
    consultaUsda: 'potatoes boiled cooked without skin',
  },
  {
    id: 'camote',
    nombre: 'Camote',
    categoria: 'carbohidrato-fuerte',
    carbs: 1,
    porcion: '1/2 taza',
    explicacion: 'Mejor que la papa, pero cuenta como carbohidrato.',
    icono: 'icon-bowl',
    semaforo: 'amarillo',
    consultaUsda: 'sweet potato cooked boiled',
  },

  // ── Carbohidratos medios: 0.5 puntos, se pueden combinar ─────────
  {
    id: 'tortilla',
    nombre: 'Tortilla de maiz',
    categoria: 'carbohidrato-medio',
    carbs: 0.5,
    porcion: '1 pieza',
    explicacion: 'Maximo 2 tortillas por comida.',
    icono: 'icon-bread',
    semaforo: 'amarillo',
    consultaUsda: 'corn tortilla',
  },
  {
    id: 'frijoles',
    nombre: 'Frijoles de la olla',
    categoria: 'carbohidrato-medio',
    carbs: 0.5,
    porcion: '1/2 taza',
    explicacion: 'Frijoles con aguacate: te llenan sin picos.',
    icono: 'icon-seedling',
    semaforo: 'amarillo',
    consultaUsda: 'beans pinto cooked boiled',
  },
  {
    id: 'lentejas',
    nombre: 'Lentejas',
    categoria: 'carbohidrato-medio',
    carbs: 0.5,
    porcion: '1/2 taza',
    explicacion: 'Proteinas y fibra juntas.',
    icono: 'icon-seedling',
    semaforo: 'amarillo',
    consultaUsda: 'lentils mature seeds cooked boiled',
  },
  {
    id: 'avena',
    nombre: 'Avena',
    categoria: 'carbohidrato-medio',
    carbs: 0.5,
    porcion: '1/2 taza',
    explicacion: 'Ideal para el desayuno con fruta y frutos secos.',
    icono: 'icon-wheat',
    semaforo: 'amarillo',
    consultaUsda: 'oats cooked regular quick',
  },

  // ── Grasas buenas: libres ────────────────────────────────────────
  {
    id: 'aguacate',
    nombre: 'Aguacate',
    categoria: 'grasa',
    carbs: 0,
    porcion: '1/4 pieza',
    explicacion: 'Grasa buena que baja los picos de azucar.',
    icono: 'icon-avocado',
    semaforo: 'verde',
    consultaUsda: 'avocados raw california',
  },
  {
    id: 'nueces',
    nombre: 'Nueces',
    categoria: 'grasa',
    carbs: 0,
    porcion: '5 piezas',
    explicacion: 'Un punado entre comidas quita el hambre.',
    icono: 'icon-sphere',
    semaforo: 'verde',
    consultaUsda: 'nuts walnuts english',
  },
  {
    id: 'almendras',
    nombre: 'Almendras',
    categoria: 'grasa',
    carbs: 0,
    porcion: '10 piezas',
    explicacion: 'Muy buenas para el corazon.',
    icono: 'icon-sphere',
    semaforo: 'verde',
    consultaUsda: 'nuts almonds',
  },
  {
    id: 'cacahuates',
    nombre: 'Cacahuates naturales',
    categoria: 'grasa',
    carbs: 0,
    porcion: '1/4 taza',
    explicacion: 'Sin sal ni azucar, mejor.',
    icono: 'icon-sphere',
    semaforo: 'verde',
    consultaUsda: 'peanuts all types raw',
  },
];

export const maxPuntosCarbohidrato = 1;
export const maxTortillasComida = 2;

export const alimentosPorId = (id: string): Alimento | undefined =>
  alimentos.find((a) => a.id === id);